exclude: ^(notebooks|data)
repos:
-   repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
    -   id: trailing-whitespace
        exclude: '.*\.fits$'
    -   id: end-of-file-fixer
        exclude_types: [csv]
        exclude: '.*\.fits$'
    -   id: check-yaml
    -   id: check-added-large-files
- repo: https://github.com/psf/black
  rev: 23.10.1
  hooks:
    - id: black
- repo: https://github.com/pycqa/isort
  rev: 5.12.0
  hooks:
    - id: isort
